baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5
	
[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Georgios Karamanis"
    subtitle = "photography and data visualization"
    keywords = "photography dataviz"
    copyright = "Â© 2009-2020"
    menuMore = "stuff"
    writtenBy = "by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Georgios Karamanis"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
		weight = 3
	
      [[languages.en.menu.main]]
        identifier = "dataviz"
        name = "dataviz"
        url = "/dataviz"
		weight = 2
		
      [[languages.en.menu.main]]
        identifier = "street"
        name = "street"
        url = "/street"
	
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/blog"
		weight = 1

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "archive"
        url = "/archive"